-- mysql -u root -p
-- 123456

DROP DATABASE IF EXISTS Academia;
CREATE DATABASE Academia;
--EJERCICIO 1

USE Academia;

DROP TABLE IF EXISTS PROFESORES;
DROP TABLE IF EXISTS CURSOS;
DROP TABLE IF EXISTS ALUMNOS;

/*CREACION DE TABLAS*/

CREATE TABLE PROFESORES(
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50) UNIQUE,
    APELLIDO1 VARCHAR(50),
    APELLIDO2 VARCHAR(50),
    DIRECCION VARCHAR(50),
    TITULO VARCHAR(100),
    GANA DECIMAL(6,2) NOT NULL
);

CREATE TABLE CURSOS(
    COD_CURSO INT(8) PRIMARY KEY,
    NOMBRE_CURSOS VARCHAR(100) UNIQUE,
    DNI_PROFESOR VARCHAR(9),
    MAXIMO_ALUMNOS INT(4),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS INT(4) NOT NULL,
    CONSTRAINT fk_DNI_PROFESOR FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI),
    CONSTRAINT check_fechas CHECK(FECHA_INICIO<FECHA_FIN)
);

CREATE TABLE ALUMNOS(
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO1 VARCHAR(50),
    APELLIDO2 VARCHAR(50),
    DIRECCION VARCHAR(100),
    SEXO CHAR(1),
    FECHA_NACIMIENTO DATE,
    CURSO INT(8) NOT NULL,
    CONSTRAINT fk_CURSO FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO),
    CONSTRAINT check_sexo CHECK (SEXO ='H' OR SEXO = 'M')
);
