system cls --limpiar consola

DELETE FROM ALUMNOS;
DELETE FROM CURSOS;
DELETE FROM PROFESORES;

--EJERCICIO 2
--Insertar las siguientes tuplas:
INSERT INTO PROFESORES(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TITULO,GANA)
VALUES('32432455','Juan','Arch','López','Puerta Negra 4','Ing. Informatica',7500);

INSERT INTO PROFESORES(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,TITULO,GANA)
VALUES('43215643','Maria','Oliva','Rubio','Juan Alfonso 32','Lda. Fil. Inglesa',5400);

INSERT INTO CURSOS(COD_CURSO,NOMBRE_CURSOS,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUE(1,'Ingles Basico','43215643',15,'2000-11-01','2000-12-22',120);

INSERT INTO CURSOS(COD_CURSO,NOMBRE_CURSOS,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN,NUM_HORAS)
VALUE(2,'Administración Linux','32432455',null,'2000-10-01',null,80);

INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('123523','Lucas','Manilva','López','Alhamar 3','H','1979-11-01',1);

INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('2567567','Antonia','López','Alcantara','Maniqui 21','M',null,2);

INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('3123689','Manuel','Alcantara','Pedrós','Julian 2',null,null,2);

INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('4896765','José','Pérez','Caballar','Jarcha 5','H','1977-02-03',1);

--EJERCICIO 3
--Insertar la siguiente tupla en ALUMNOS:
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO,COD_CURSO)
VALUES('Sergio','Navas','Retal','123523',null,'H',null,null,null);
/*No deja: La clave primaria esta duplicada*/

--EJERCICIO 4
--Añadir el campo edad de tipo numérico a la tabla PROFESORES.
ALTER TABLE PROFESORES ADD EDAD INT(2);

--NOTA:
/*Ver tipos de datos por consulta*/
SHOW CREATE TABLE PROFESORES;


--EJERCICIO 5
/*Añadir las siguientes restricciones:
a-La edad de los profesores está entre 18 y 65 años.
b-No se puede añadir un curso si su número de alumnos máximo es menor que 10.
c-El número de horas de los cursos debe ser mayor que 100.*/
ALTER TABLE PROFESORES
ADD CONSTRAINT CHECK_EDAD CHECK (EDAD >=18 && EDAD <=65);

ALTER TABLE CURSOS
ADD CONSTRAINT CHECK_MIN_ALUMNOS CHECK (MAXIMO_ALUMNOS > 9);

UPDATE CURSOS
SET NUM_HORAS = 120 WHERE COD_CURSO = 2;

ALTER TABLE CURSOS
ADD CONSTRAINT CHECK_NUM_HORAS CHECK (NUM_HORAS > 100);

/*EJERCICIO 6*/
ALTER TABLE ALUMNOS
DROP CONSTRAINT CHECK_SEXO;

/*EJERCICIO 7*/
/* NO PORQUE SI LANZAMOS LA SENTENCIA UNIQUE CADA ALUMNO 
SOLO PODRIA PERTENER A UN UNICO CURSO, SI HAY 30 ALUMNOS DEBERÍA HABER
30 CURSOS, UNO POR ALUMNO

LA CONSULTA SE LANZARIA

ALTER TABLE ALUMNOS
ADD CONSTRAINT CURSOS_UNIQUE UNIQUE(CURSO);
*/

/*EJERCICIO 8*/
ALTER TABLE PROFESORES
MODIFY GANA DECIMAL(6,2);


/*EJERCICIO 9*/
ALTER TABLE CURSOS
MODIFY FECHA_INICIO DATE NOT NULL;


/*EJERCICIO 10*/
ALTER TABLE CURSOS
DROP FOREIGN KEY FK_PROFESOR;

ALTER TABLE PROFESORES
DROP PRIMARY KEY;

ALTER TABLE PROFESORES
MODIFY DNI VARCHAR(9) PRIMARY KEY NOT NULL;

ALTER TABLE CURSOS
ADD CONSTRAINT FK_PROFESOR FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI);
/*NO SE PUEDE HACER PORQUE YA TENEMOS DATOS INTRODUCIDOS 
SI NO TUVIESEMOS DATOS SE PODRÍA HACER SIN PROBLEMA*/

/*EJERCICIO 11*//*Los datos de insercion son erroneos*/
INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('32432455','Juan','Arch','Lopez','Puerta Negra 4','H',null,null);

INSERT INTO ALUMNOS(DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,SEXO,FECHA_NACIMIENTO,CURSO)
VALUES('789678','Maria','Jaen','Sevilla','Martos 5','M','1977-03-10',null);

/*EJERCICIO 12*/
UPDATE ALUMNOS SET FECHA_NACIMIENTO = '1976-12-23' WHERE DNI = '2567567';

/*EJERCICIO 13*/
UPDATE ALUMNOS SET CURSO = 5 WHERE DNI = '2567567';
/*NO SE PUEDE YA QUE EL CURSO 5 NO EXISTE Y COMO
TIENE UN FK NO PUEDE AÑADIRLO AL NO EXISTIR*/


/*EJERCICIO 14*/
DELETE FROM PROFESORES WHERE NOMBRE = 'Laura Jimenez';

/*NO EXISTE LA PROFESORA LAURA JIMENEZ*/


/*EJERCICIO 15*/
CREATE temporary TABLE NOMBRE_ALUMNOS
    SELECT CONCAT (NOMBRE, ' ', APELLIDO1, ' ', APELLIDO2)
    AS NOMBRE_COMPLETO FROM ALUMNOS;
